/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Inside.*;

/**
 * @author Sergio Segura
 */

public class Administar extends javax.swing.JFrame {

    Botones bot = new Botones();
    ContraseñaT1 pass = new ContraseñaT1();
    Logica log = new  Logica();
    
    int num;
    
    public Administar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bot_MenuPrincipal = new javax.swing.JButton();
        botRegistrar = new javax.swing.JButton();
        botBusqueda = new javax.swing.JButton();
        botEstadisticas = new javax.swing.JButton();
        botInformacion = new javax.swing.JButton();
        correrSentencia = new javax.swing.JButton();
        cambiarDatos = new javax.swing.JButton();
        limpiarTabla = new javax.swing.JButton();
        borrarCliente = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bot_MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botMenuPrincipal.png"))); // NOI18N
        Bot_MenuPrincipal.setBorderPainted(false);
        Bot_MenuPrincipal.setContentAreaFilled(false);
        Bot_MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_MenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 25, 180, 170));

        botRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botRegistar.png"))); // NOI18N
        botRegistrar.setBorderPainted(false);
        botRegistrar.setContentAreaFilled(false);
        botRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 40));

        botBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botBusqueda.png"))); // NOI18N
        botBusqueda.setBorderPainted(false);
        botBusqueda.setContentAreaFilled(false);
        botBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(botBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 40));

        botEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botEstadisticas.png"))); // NOI18N
        botEstadisticas.setBorderPainted(false);
        botEstadisticas.setContentAreaFilled(false);
        botEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(botEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        botInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botInformacion.png"))); // NOI18N
        botInformacion.setBorderPainted(false);
        botInformacion.setContentAreaFilled(false);
        botInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(botInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 230, 40));

        correrSentencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bot_Ad004.png"))); // NOI18N
        correrSentencia.setBorderPainted(false);
        correrSentencia.setContentAreaFilled(false);
        correrSentencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correrSentenciaActionPerformed(evt);
            }
        });
        getContentPane().add(correrSentencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 342, 150, 150));

        cambiarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bot_Ad001.png"))); // NOI18N
        cambiarDatos.setBorderPainted(false);
        cambiarDatos.setContentAreaFilled(false);
        cambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 345, 150, 150));

        limpiarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bot_Ad002.png"))); // NOI18N
        limpiarTabla.setBorderPainted(false);
        limpiarTabla.setContentAreaFilled(false);
        limpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTablaActionPerformed(evt);
            }
        });
        getContentPane().add(limpiarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 342, 150, 150));

        borrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bot_Ad003.png"))); // NOI18N
        borrarCliente.setBorderPainted(false);
        borrarCliente.setContentAreaFilled(false);
        borrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(borrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 342, 150, 150));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/baseAdministar.png"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot_MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_MenuPrincipalActionPerformed
        bot.abrirMenuPrincipal();
        this.setVisible(false);
    }//GEN-LAST:event_Bot_MenuPrincipalActionPerformed

    private void botRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRegistrarActionPerformed
        bot.abrirRegistar();
        this.setVisible(false);
    }//GEN-LAST:event_botRegistrarActionPerformed

    private void botBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBusquedaActionPerformed
        bot.abrirBusqueda();
        this.setVisible(false);
    }//GEN-LAST:event_botBusquedaActionPerformed

    private void botEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEstadisticasActionPerformed
        bot.abrirEstadisticas();
        this.setVisible(false);
    }//GEN-LAST:event_botEstadisticasActionPerformed

    private void botInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInformacionActionPerformed
        bot.abrirInformacion();
        this.setVisible(false);
    }//GEN-LAST:event_botInformacionActionPerformed

    private void cambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarDatosActionPerformed
        log.seleccionarTipo1();
        this.setVisible(false);
        bot.abrirMenuCOD();
    }//GEN-LAST:event_cambiarDatosActionPerformed

    private void limpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTablaActionPerformed
        bot.abrirContraseñaT1();
        this.setVisible(false);
    }//GEN-LAST:event_limpiarTablaActionPerformed

    private void borrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarClienteActionPerformed
        log.seleccionarTipo2();
        this.setVisible(false);
        bot.abrirMenuCOD();
    }//GEN-LAST:event_borrarClienteActionPerformed

    private void correrSentenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correrSentenciaActionPerformed
        bot.abrirContraseñaT2();
        this.setVisible(false);
    }//GEN-LAST:event_correrSentenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_MenuPrincipal;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton borrarCliente;
    private javax.swing.JButton botBusqueda;
    private javax.swing.JButton botEstadisticas;
    private javax.swing.JButton botInformacion;
    private javax.swing.JButton botRegistrar;
    private javax.swing.JButton cambiarDatos;
    private javax.swing.JButton correrSentencia;
    private javax.swing.JButton limpiarTabla;
    // End of variables declaration//GEN-END:variables

    
}
