package Interface;

import Inside.Botones;

/**
 * @author Sergio Segura
 */

public class Busqueda extends javax.swing.JFrame 
{

    Botones bot = new Botones();

    //Variables del indice d busqueda
    public static String indice = "Nombre";
    public static String clave = " ";

    /**
     * Creates new form Busqueda
     */
    public Busqueda() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTLugar = new javax.swing.JToggleButton();
        jTCod = new javax.swing.JToggleButton();
        jTFecga = new javax.swing.JToggleButton();
        jTNombre = new javax.swing.JToggleButton();
        BotRegistro = new javax.swing.JButton();
        BotAdministracion = new javax.swing.JButton();
        BotEstadisticas = new javax.swing.JButton();
        BotInformacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Bot_MenuPrincipal1 = new javax.swing.JButton();
        cBusqueda = new javax.swing.JTextField();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botLugar.png"))); // NOI18N
        jTLugar.setSelected(true);
        jTLugar.setBorderPainted(false);
        jTLugar.setContentAreaFilled(false);
        jTLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTLugarActionPerformed(evt);
            }
        });
        getContentPane().add(jTLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 200, 150, 40));

        jTCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botId.png"))); // NOI18N
        jTCod.setSelected(true);
        jTCod.setBorderPainted(false);
        jTCod.setContentAreaFilled(false);
        jTCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 140, 40));

        jTFecga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botFecha.png"))); // NOI18N
        jTFecga.setSelected(true);
        jTFecga.setBorderPainted(false);
        jTFecga.setContentAreaFilled(false);
        jTFecga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFecgaActionPerformed(evt);
            }
        });
        getContentPane().add(jTFecga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 160, 40));

        jTNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botNombre.png"))); // NOI18N
        jTNombre.setSelected(true);
        jTNombre.setBorderPainted(false);
        jTNombre.setContentAreaFilled(false);
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 140, 40));

        BotRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botRegistar.png"))); // NOI18N
        BotRegistro.setBorderPainted(false);
        BotRegistro.setContentAreaFilled(false);
        BotRegistro.setDefaultCapable(false);
        BotRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 40));

        BotAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botAdministrar.png"))); // NOI18N
        BotAdministracion.setBorderPainted(false);
        BotAdministracion.setContentAreaFilled(false);
        BotAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAdministracionActionPerformed(evt);
            }
        });
        getContentPane().add(BotAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 40));

        BotEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botEstadisticas.png"))); // NOI18N
        BotEstadisticas.setBorderPainted(false);
        BotEstadisticas.setContentAreaFilled(false);
        BotEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(BotEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        BotInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botInformacion.png"))); // NOI18N
        BotInformacion.setBorderPainted(false);
        BotInformacion.setContentAreaFilled(false);
        BotInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(BotInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 230, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lupa.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 70, 70));

        Bot_MenuPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botMenuPrincipal.png"))); // NOI18N
        Bot_MenuPrincipal1.setBorderPainted(false);
        Bot_MenuPrincipal1.setContentAreaFilled(false);
        Bot_MenuPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_MenuPrincipal1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_MenuPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 25, 180, 170));

        cBusqueda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 210, 30));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/baseBusqueda.png"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTLugarActionPerformed
        indice = "Lugar";
    }//GEN-LAST:event_jTLugarActionPerformed

    private void jTCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodActionPerformed
        indice = "cod";
    }//GEN-LAST:event_jTCodActionPerformed

    private void jTFecgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFecgaActionPerformed
        indice = "Fecha";
    }//GEN-LAST:event_jTFecgaActionPerformed

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        indice = "Nombre";
    }//GEN-LAST:event_jTNombreActionPerformed

    private void BotRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRegistroActionPerformed
        bot.abrirRegistar();
        this.setVisible(false);
    }//GEN-LAST:event_BotRegistroActionPerformed

    private void BotAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAdministracionActionPerformed
        bot.abrirAdministrar();
        this.setVisible(false);
    }//GEN-LAST:event_BotAdministracionActionPerformed

    private void BotEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEstadisticasActionPerformed
        bot.abrirEstadisticas();
        this.setVisible(false);
    }//GEN-LAST:event_BotEstadisticasActionPerformed

    private void BotInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInformacionActionPerformed
        bot.abrirInformacion();
        this.setVisible(false);
    }//GEN-LAST:event_BotInformacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        clave = (this.cBusqueda.getText()).toUpperCase();
        this.setVisible(false);
        Resultado Fmostrar = new Resultado();
        Fmostrar.setVisible(true);
        Fmostrar.pack();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Bot_MenuPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_MenuPrincipal1ActionPerformed
        bot.abrirMenuPrincipal();
        this.setVisible(false);
    }//GEN-LAST:event_Bot_MenuPrincipal1ActionPerformed

    private void cBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAdministracion;
    private javax.swing.JButton BotEstadisticas;
    private javax.swing.JButton BotInformacion;
    private javax.swing.JButton BotRegistro;
    private javax.swing.JButton Bot_MenuPrincipal1;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JTextField cBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jTCod;
    private javax.swing.JToggleButton jTFecga;
    private javax.swing.JToggleButton jTLugar;
    private javax.swing.JToggleButton jTNombre;
    // End of variables declaration//GEN-END:variables
}
