package Interface;

import Inside.Botones;
import Inside.Logica;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * @author Sergio Segura
 */

public class CambiarDatos extends javax.swing.JFrame 
{
   
    Botones bot = new Botones();
    
    static Connection cn;
    static Statement st;
    static ResultSet rs;
    
    private String  elemSelect;
    private String  nuevoDato;
    
    String consulta;
    
    private static String cod = " ";
    
    public CambiarDatos() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        change();
    }
    
    public void generarConsulta ()
    {
        nuevoDato = (JOptionPane.showInputDialog("Coloque el nuevo dato "+elemSelect).toUpperCase());
        consulta = "update clientes set "+elemSelect+" = '"+nuevoDato+"' where cod = '"+cod+"'";
        System.out.println(consulta);
        cambiarDatos();
    }
    
    public void change ()
    {
        jTcod.setText("SSV6");
        jTnombre.setText("SERGIO SEGURA VIDAL");
        jTfecha.setText("05/07/15");
    }
       
    public static void setCod(String cod) 
    {
        CambiarDatos.cod = cod;
    }
    
    public void cambiarDatos()
    {
        try
        {
           cn = Logica.Enlace(cn);
           rs=Logica.EnlEst(rs,consulta);
           System.out.println(consulta);
           JOptionPane.showMessageDialog(null, "Se ha cambiado el dato satisfactoriamente");
           bot.abrirAdministrar();
           this.setVisible(false);
           rs.close();
           cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "se ha producido un erro al \n cambiar los datos: \n"+e);
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bot_MenuPrincipal = new javax.swing.JButton();
        botRegistrar = new javax.swing.JButton();
        botBusqueda = new javax.swing.JButton();
        botAdministrar = new javax.swing.JButton();
        botEstadisticas = new javax.swing.JButton();
        botInformacion = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTfecha = new javax.swing.JTextField();
        jTcod = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bot_MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botMenuPrincipal.png"))); // NOI18N
        Bot_MenuPrincipal.setBorderPainted(false);
        Bot_MenuPrincipal.setContentAreaFilled(false);
        Bot_MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_MenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 25, 180, 170));

        botRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botRegistar.png"))); // NOI18N
        botRegistrar.setBorderPainted(false);
        botRegistrar.setContentAreaFilled(false);
        botRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

        botBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botBusqueda.png"))); // NOI18N
        botBusqueda.setBorderPainted(false);
        botBusqueda.setContentAreaFilled(false);
        botBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(botBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 40));

        botAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botAdministrar.png"))); // NOI18N
        botAdministrar.setBorderPainted(false);
        botAdministrar.setContentAreaFilled(false);
        botAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(botAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 40));

        botEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botEstadisticas.png"))); // NOI18N
        botEstadisticas.setBorderPainted(false);
        botEstadisticas.setContentAreaFilled(false);
        botEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(botEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 40));

        botInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/botInformacion.png"))); // NOI18N
        botInformacion.setBorderPainted(false);
        botInformacion.setContentAreaFilled(false);
        botInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(botInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jComboBox1.setFont(new java.awt.Font("ETH", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fecha", "nombre", "lugar", "tel", "areaLote", "areaConst", "precio", "correo", "otrosDatos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 160, 30));

        jTfecha.setEditable(false);
        jTfecha.setFont(new java.awt.Font("ETH", 0, 18)); // NOI18N
        jTfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfecha.setText("jTextField1");
        getContentPane().add(jTfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 140, 30));

        jTcod.setEditable(false);
        jTcod.setFont(new java.awt.Font("ETH", 0, 18)); // NOI18N
        jTcod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTcod.setText("jTextField1");
        getContentPane().add(jTcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 30));

        jTnombre.setEditable(false);
        jTnombre.setFont(new java.awt.Font("ETH", 0, 18)); // NOI18N
        jTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTnombre.setText("jTextField1");
        getContentPane().add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bot_cambiar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 475, 170, 40));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/baseCambiarDatos.png"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot_MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_MenuPrincipalActionPerformed
        bot.abrirMenuPrincipal();
        this.setVisible(false);
    }//GEN-LAST:event_Bot_MenuPrincipalActionPerformed

    private void botRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRegistrarActionPerformed
        bot.abrirRegistar();
        this.setVisible(false);
    }//GEN-LAST:event_botRegistrarActionPerformed

    private void botBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBusquedaActionPerformed
        bot.abrirBusqueda();
        this.setVisible(false);
    }//GEN-LAST:event_botBusquedaActionPerformed

    private void botAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdministrarActionPerformed
        bot.abrirBusqueda();
        this.setVisible(false);
    }//GEN-LAST:event_botAdministrarActionPerformed

    private void botEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEstadisticasActionPerformed
        bot.abrirEstadisticas();
        this.setVisible(false);
    }//GEN-LAST:event_botEstadisticasActionPerformed

    private void botInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInformacionActionPerformed
        bot.abrirInformacion();
        this.setVisible(false);
    }//GEN-LAST:event_botInformacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       generarConsulta();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        JComboBox x = (JComboBox)evt.getSource();
        elemSelect = (String) x.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_MenuPrincipal;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton botAdministrar;
    private javax.swing.JButton botBusqueda;
    private javax.swing.JButton botEstadisticas;
    private javax.swing.JButton botInformacion;
    private javax.swing.JButton botRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTcod;
    private javax.swing.JTextField jTfecha;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
